const feedUrl = "https://extropyengine.com/podcast/feed.xml";
const researchLogFeedUrl = "https://extropyengine.com/podcast-log/feed.xml";
const redactedFeedUrl = "https://extropyengine.com/podcast-redacted/feed.xml";

export const podcast = {
  title: "Extropy Engine",
  author: "Randall Gossett",
  tagline: "Talk. Field notes. Loops.",
  description:
    "A channel for the stuff that doesn’t want to be a paper. Spotify, YouTube, and Apple are live. Anyone else: take the RSS. This website is not the Engine. The diary stays on the box.",
  feedPath: "/podcast/feed.xml",
  feedUrl,
  cover: "/podcast/cover.jpg",
  page: "/podcast",
  spotify: "https://open.spotify.com/show/7G9pK1dHFCam95qQlFAMNE",
  youtube: "https://www.youtube.com/@Lladnaros/podcasts",
  apple: "https://extropyengine.com/podcast/feed.xml",
} as const;

export const researchLog = {
  title: "Extropy Engine Research Pod",
  author: "Randall Gossett",
  tagline: "Automated. Unsigned. Not the Codex.",
  description:
    "AUTOMATED RESEARCH POD. Episodes are generated by AI from Extropy Engine research notes and cited sources (Gemini / NotebookLM audio overviews). They are not reviewed, not edited, and not signed by Randall Gossett. Unsigned trail. Not the Codex. Not a paper. Not legal, medical, investment, or protocol advice. Adjacent papers mentioned in an episode do not prove the Engine. The live protocol is the git. Signed book and papers live on this site. If this feed conflicts with those, those win.",
  feedPath: "/podcast-log/feed.xml",
  feedUrl: researchLogFeedUrl,
  cover: "/podcast-log/cover.jpg",
  page: "/research-pod",
} as const;

export const redacted = {
  title: "Extropy Engine Redacted",
  author: "Randall Gossett",
  tagline: "Old meter. Trail. Not the Codex.",
  description:
    "Archived episodes. Not current protocol. Do not use as a source for meters, leak, or tokens. Live talk is /podcast. Letters: /key.",
  feedPath: "/podcast-redacted/feed.xml",
  feedUrl: redactedFeedUrl,
  cover: "/podcast-redacted/cover.jpg",
  page: "/redacted",
} as const;

export const subscribeApps = [
  {
    id: "spotify",
    label: "Spotify",
    hint: "live",
    href: podcast.spotify,
  },
  {
    id: "youtube",
    label: "YouTube",
    hint: "live",
    href: podcast.youtube,
  },
  {
    id: "apple",
    label: "Apple Podcasts",
    hint: "live",
    href: podcast.apple,
  },
] as const;

export const featuredSeries = {
  name: "The Engine in Plain Words",
  tagline: "Start here.",
  description:
    "Four episodes with Vic and Ron that explain the entire Extropy Engine in plain spoken language: the apps you touch, the movement that powers it, the protocol that runs it, and how it all connects. If you are new, this is the front door.",
  cover: "/podcast/plain-words-cover-16x9.jpg",
  episodes: [
    {
      part: "Part 1",
      title: "The Apps",
      src: "/podcast/2026-10-02-the-engine-in-plain-words-part-1-the-apps.mp3",
      duration: "8:08",
    },
    {
      part: "Part 2",
      title: "The Movement",
      src: "/podcast/2026-10-02-the-engine-in-plain-words-part-2-the-movement.mp3",
      duration: "8:36",
    },
    {
      part: "Part 3",
      title: "The Protocol",
      src: "/podcast/2026-10-02-the-engine-in-plain-words-part-3-the-protocol.mp3",
      duration: "8:24",
    },
    {
      part: "Part 4",
      title: "How It All Connects",
      src: "/podcast/2026-10-02-the-engine-in-plain-words-part-4-how-it-all-connects.mp3",
      duration: "8:57",
    },
  ],
} as const;
