const feedUrl = "https://extropyengine.com/podcast/feed.xml";
const researchLogFeedUrl = "https://extropyengine.com/podcast-log/feed.xml";

export const podcast = {
  title: "Extropy Engine",
  author: "Randall Gossett",
  tagline: "Talk. Field notes. Loops.",
  description:
    "A channel for the stuff that doesn’t want to be a paper. Spotify and YouTube are live. Anyone else: take the RSS. This website is not the Engine. The diary stays on the box.",
  feedPath: "/podcast/feed.xml",
  feedUrl,
  cover: "/podcast/cover.jpg",
  page: "/podcast",
  spotify: "https://open.spotify.com/show/7G9pK1dHFCam95qQlFAMNE",
  youtube: "https://www.youtube.com/@Lladnaros/podcasts",
} as const;

export const researchLog = {
  title: "Extropy Engine Research Pod",
  author: "Randall Gossett",
  tagline: "Automated. Unsigned. Not the Codex.",
  description:
    "AUTOMATED RESEARCH POD. Episodes are generated by AI from Extropy Engine research notes and cited sources (Gemini / NotebookLM audio overviews). They are not reviewed, not edited, and not signed by Randall Gossett. Unsigned trail. Not the Codex. Not a paper. Not legal, medical, investment, or protocol advice. Adjacent papers mentioned in an episode do not prove the Engine. The live protocol is the git. Signed book and papers live on this site. If this feed conflicts with those, those win.",
  feedPath: "/podcast-log/feed.xml",
  feedUrl: researchLogFeedUrl,
  cover: "/podcast-log/cover.jpg",
  page: "/research-pod",
} as const;

export const subscribeApps = [
  {
    id: "spotify",
    label: "Spotify",
    hint: "live",
    href: podcast.spotify,
  },
  {
    id: "youtube",
    label: "YouTube",
    hint: "live",
    href: podcast.youtube,
  },
] as const;
