/** Single source for letters. If a page disagrees with this file, this file wins. */
export const symbolKey = {
  title: "Letter key",
  kicker: "Do not remap these",
  lead: "Same Latin letter gets reused in every field. Here is what this protocol means. Not reputation. Not falsifiability. Not “weighted emergence.” The most recent signed Codex is v2.1. Canonical mint in code is v3.1.2 in packages/xp-formula. If a chatbot invents a third reading, it is wrong.",
  formula: "XP = R × F × ΔS × (w · E) × log(1/Tₛ)",
  mint: [
    {
      id: "r",
      glyph: "R",
      name: "Rarity",
      is: "Scarcity / base difficulty of this action class. Property of the loop, not the person. Range [0.1, 10].",
      isNot: "Not reputation. Not how famous the actor is.",
    },
    {
      id: "f",
      glyph: "F",
      name: "Frequency of Decay",
      is: "Repeating the same action class pays less. 1.0 the first time.",
      isNot: "Not falsifiability. That letter is script-ℱ below.",
    },
    {
      id: "delta-s",
      glyph: "ΔS",
      name: "Change in entropy (reduction)",
      is: "Verified entropy reduction for this loop. Must be > 0 to mint. A proxy we fine-tune. Domain-native units get a bits-equivalent so they can sit on one graph.",
      isNot: "Not XP. ΔS is the reduction. XP is the ledger stand-in after the mint.",
    },
    {
      id: "w-dot-e",
      glyph: "w · E",
      name: "Weight vector · effort / domain vector",
      is: "Dot product. w is the weight vector across the eight domains. E is the effort / domain vector for this loop (gas, ozone, alternative trip, lawn vs ride). Cross-domain terms live here. Written w · E, sometimes (w · E).",
      isNot: "Not “weighted emergence.” Not a single scalar named W.E. Not a ninth domain called Emergence. Not “waited.”",
    },
    {
      id: "ts",
      glyph: "Tₛ",
      name: "Slam window",
      is: "Elapsed time of this loop. Tₛ = exp(−λ min(Δt, Δt_cap)). Then log(1/Tₛ) = λ · clip(Δt). Instant close (Δt → 0) → Tₛ = 1 → log = 0 → XP = 0, on purpose.",
      isNot: "Not recency decay. Not the 0.99ⁿ standing leak. Do not rewrite as log(1+1/Tₛ).",
    },
    {
      id: "lambda",
      glyph: "λ",
      name: "Slam rate",
      is: "Knob inside Tₛ. Scales how fast the slam window opens with elapsed Δt.",
      isNot: "Not the standing leak.",
    },
    {
      id: "dt",
      glyph: "Δt",
      name: "Elapsed time of this loop",
      is: "Clock start to confirm. Clipped to Δt_cap so stalling is not a mint.",
      isNot: "Not calendar age of standing XP.",
    },
  ],
  other: [
    {
      id: "xp",
      glyph: "XP",
      name: "Standing meter",
      is: "The letters are XP. Proxy of ΔS on the ledger after the mint. You do not spend it. Access economy. Decays ~1%/month of remaining (0.99ⁿ).",
      isNot: "Not “Extropy Points.” Not a cash bag. Not ΔS itself.",
    },
    {
      id: "script-f",
      glyph: "ℱ",
      name: "Falsifiability",
      is: "Script-F. A claim that can fail in the open. Lose-conditions live here.",
      isNot: "Not Frequency of Decay. Never write F for this.",
    },
    {
      id: "cl",
      glyph: "cₗ",
      name: "Causal-closure speed",
      is: "Local max rate causal effects propagate in a domain. Floor slogan: XP ≥ ΔS / cₗ². Compression of the mint, not a second theory.",
      isNot: "Not the speed of light as a new physics law. Structural analogy.",
    },
    {
      id: "l",
      glyph: "L",
      name: "Local coupling",
      is: "Fraction at this door. Feeds the till. EP = XP × L, then EP burns.",
      isNot: "Not Landauer’s constant. Not a lane.",
    },
    {
      id: "ep",
      glyph: "EP",
      name: "Emergent Product",
      is: "Till spark. Born and burned in the sale. May discount fiat. Not a bag.",
      isNot: "Not Epistemic Proof. Letter collision. Proof-layer records do not buy milk.",
    },
    {
      id: "ct",
      glyph: "CT",
      name: "Contribution standing",
      is: "Meter for this door. Feeds L. Not purchased with XP.",
      isNot: "Not a coin.",
    },
    {
      id: "cat",
      glyph: "CAT",
      name: "Skill record",
      is: "Unique. Lane + level + issuer. Off the XP mint.",
      isNot: "Not a pile of points.",
    },
    {
      id: "it",
      glyph: "IT",
      name: "Influence standing",
      is: "Governance / demonstration weight. Idle leak ~5%/month. Off the XP mint.",
      isNot: "Not Insight Token. Not a bag.",
    },
    {
      id: "leak",
      glyph: "0.99ⁿ",
      name: "Standing leak",
      is: "~1% of remaining XP per ~30 days after settlement. Half-life ~69 months. Never hits zero in the reals.",
      isNot: "Not Tₛ. Not F.",
    },
  ],
} as const;
