/** Single source for letters. If a page disagrees with this file, this file wins. */
export const symbolKey = {
  title: "Letter key",
  kicker: "Do not remap these",
  lead: "Same Latin letter gets reused in every field. CT is the community meter. Same CT at every compatible till. The door only owns H. A wrap that breaks the rules, or another mesh, is the only way the laundromat does not read the grocery. Parallel system: cash still clears. Signed Codex v2.1. Meter coupling: /docs/METER-MATH.md.",
  formula: "XP = R × F × ΔS × (w · E) × log(1/Tₛ)",
  mint: [
    {
      id: "r",
      glyph: "R",
      name: "Rarity",
      is: "Scarcity / base difficulty of this action class. Property of the loop, not the person. Range [0.1, 10].",
      isNot: "Not reputation. Not how famous the actor is.",
    },
    {
      id: "f",
      glyph: "F",
      name: "Frequency of Decay",
      is: "Repeating the same action class pays less. 1.0 the first time.",
      isNot: "Not falsifiability. That letter is script-ℱ below.",
    },
    {
      id: "delta-s",
      glyph: "ΔS",
      name: "Change in entropy (reduction)",
      is: "Verified entropy reduction for this loop. Must be > 0 to mint. A proxy we fine-tune. Domain-native units get a bits-equivalent so they can sit on one graph.",
      isNot: "Not XP. ΔS is the reduction. XP is the ledger stand-in after the mint.",
    },
    {
      id: "w-dot-e",
      glyph: "w · E",
      name: "Weighted emergence",
      is: "The product itself. w is the weight vector across the eight domains. E is the effort / domain vector for this loop. w · E is those weights applied to that effort — emergence scored across weighted domains. Lawn vs ride vs ozone lives here. PHOTON 404 says the English. The mint writes the dot product. Same object.",
      isNot: "Not a fifth letter sitting beside R, F, ΔS, and Tₛ. Not a bag named W.E. Not a ninth domain called Emergence.",
    },
    {
      id: "ts",
      glyph: "Tₛ",
      name: "Slam window",
      is: "Elapsed time of this loop. Tₛ = exp(−λ min(Δt, Δt_cap)). Then log(1/Tₛ) = λ · clip(Δt). Instant close (Δt → 0) → Tₛ = 1 → log = 0 → XP = 0, on purpose.",
      isNot: "Not recency decay. Not the 0.99ⁿ standing leak. Do not rewrite as log(1+1/Tₛ).",
    },
    {
      id: "lambda",
      glyph: "λ",
      name: "Slam rate",
      is: "Knob inside Tₛ. Scales how fast the slam window opens with elapsed Δt.",
      isNot: "Not the standing leak.",
    },
    {
      id: "dt",
      glyph: "Δt",
      name: "Elapsed time of this loop",
      is: "Clock start to confirm. Clipped to Δt_cap so stalling is not a mint.",
      isNot: "Not calendar age of standing XP.",
    },
  ],
  other: [
    {
      id: "xp",
      glyph: "XP",
      name: "Global standing",
      is: "The letters are XP. Proxy of ΔS on the ledger after the mint. Every door can see that you have standing. You do not spend it. Access economy. Decays ~1% of remaining every two weeks (0.99ⁿ). How XP works is planetary. A DFAO does not rewrite the mint. Cash-out is a lose-condition. If they vote that in, they forked.",
      isNot: "Not “Extropy Points.” Not a cash bag. Not ΔS itself. Not L. Not CT. Not Randall’s private ledger.",
    },
    {
      id: "lambda-floor",
      glyph: "λ",
      name: "Local floor",
      is: "Default 0.15. EP = XP · L + λ · L. Web W publishes one number. Eight-week notice to change.",
      isNot: "Not the slam-window λ inside Tₛ.",
    },
    {
      id: "h",
      glyph: "H_cap",
      name: "House cap this pocket",
      is: "This till this window. Auto from this door’s signed cash. Training: remainder 0 until eight weeks of signed tickets. Then clip(0.5 × cash_in / cash_out, 0, 1). No slider. No Off on the register. Unplug is Off.",
      isNot: "Not S. Not CT. Not a wrap. Not wages. Not a cashier toy.",
    },
    {
      id: "s",
      glyph: "S",
      name: "This person at this house",
      is: "Door-personal standing. Default 1 until this door has history. Fake-proof and spite cut S for 14 days.",
      isNot: "Not H_cap. Not CT_W. Not XP.",
    },
    {
      id: "script-f",
      glyph: "ℱ",
      name: "Falsifiability",
      is: "Script-F. A claim that can fail in the open. Lose-conditions live here.",
      isNot: "Not Frequency of Decay. Never write F for this.",
    },
    {
      id: "cl",
      glyph: "cₗ",
      name: "Causal-closure speed",
      is: "Local max rate causal effects propagate in a domain. Floor slogan: XP ≥ ΔS / cₗ². Compression of the mint, not a second theory.",
      isNot: "Not the speed of light as a new physics law. Structural analogy.",
    },
    {
      id: "l",
      glyph: "L",
      name: "Literal standing at this till",
      is: "This ticket. L = clip(H_cap · S · κ · CT_W · β, 0, 1). EP = XP · L + λ · L. World / town web / this house this person / this proof. CAT feeds β. Official skins show cash and the remainder.",
      isNot: "Not sweeping floors. Not Landauer. Not a secret coupon. Not global XP. Not a mesh broadcast of the diary.",
    },
    {
      id: "ep",
      glyph: "EP",
      name: "Emergent Product",
      is: "Till spark. Born and burned in the sale. Early mesh: pennies off a fiat ticket. Dense mesh: can clear more of what you owe. Not a bag.",
      isNot: "Not Epistemic Proof. Letter collision. Proof-layer records do not buy milk.",
    },
    {
      id: "ct",
      glyph: "CT",
      name: "Community standing",
      is: "Community standing on web W — DFAOs that still read base CT one-to-one. Same CT at the grocery and the laundromat until someone wraps. Idle leak 0.99ⁿ (~1% every two weeks), same keep as XP. A close, till spark, or posted task on W resets the clock. Does not travel to the next town.",
      isNot: "Not a coin. Not a job application. Not global XP. Not L itself.",
    },
    {
      id: "cat",
      glyph: "CAT",
      name: "Skill record",
      is: "Unique. Lane + level + issuer. Off the XP mint. Feeds β this ticket when on-duty. Issuer attests. DID holds the record. Spite revoke is on the issuer. Not a CT wrap.",
      isNot: "Not a pile of points.",
    },
    {
      id: "it",
      glyph: "IT",
      name: "Influence standing",
      is: "This-proposal standing. IT = clip(H_gov · S_gov · κ · CT_W · β_gov, 0, 1). Burns in the tally. No pile. Not XP · G.",
      isNot: "Not Insight Token. Not a bag. Not a 5% leak on a gavel you keep.",
    },
    {
      id: "leak",
      glyph: "0.99ⁿ",
      name: "Standing leak",
      is: "Two standing clocks plus a gavel that is not a clock. XP 0.99ⁿ. CT 0.99ⁿ idle on that web. n is idle two-week counts. IT is recomputed each proposal and burned in the tally.",
      isNot: "Not Tₛ. Not F.",
    },
  ],
} as const;
