/** Single source for letters. If a page disagrees with this file, this file wins. */
export const symbolKey = {
  title: "Letter key",
  kicker: "Do not remap these",
  lead: "Same Latin letter gets reused in every field. Here is what this protocol means. Not reputation. Not falsifiability. The most recent signed Codex is v2.1. Canonical mint in code is v3.1.2 in packages/xp-formula. If a chatbot invents a third reading, it is wrong.",
  formula: "XP = R × F × ΔS × (w · E) × log(1/Tₛ)",
  mint: [
    {
      id: "r",
      glyph: "R",
      name: "Rarity",
      is: "Scarcity / base difficulty of this action class. Property of the loop, not the person. Range [0.1, 10].",
      isNot: "Not reputation. Not how famous the actor is.",
    },
    {
      id: "f",
      glyph: "F",
      name: "Frequency of Decay",
      is: "Repeating the same action class pays less. 1.0 the first time.",
      isNot: "Not falsifiability. That letter is script-ℱ below.",
    },
    {
      id: "delta-s",
      glyph: "ΔS",
      name: "Change in entropy (reduction)",
      is: "Verified entropy reduction for this loop. Must be > 0 to mint. A proxy we fine-tune. Domain-native units get a bits-equivalent so they can sit on one graph.",
      isNot: "Not XP. ΔS is the reduction. XP is the ledger stand-in after the mint.",
    },
    {
      id: "w-dot-e",
      glyph: "w · E",
      name: "Weighted emergence",
      is: "The product itself. w is the weight vector across the eight domains. E is the effort / domain vector for this loop. w · E is those weights applied to that effort — emergence scored across weighted domains. Lawn vs ride vs ozone lives here. PHOTON 404 says the English. The mint writes the dot product. Same object.",
      isNot: "Not a fifth letter sitting beside R, F, ΔS, and Tₛ. Not a bag named W.E. Not a ninth domain called Emergence.",
    },
    {
      id: "ts",
      glyph: "Tₛ",
      name: "Slam window",
      is: "Elapsed time of this loop. Tₛ = exp(−λ min(Δt, Δt_cap)). Then log(1/Tₛ) = λ · clip(Δt). Instant close (Δt → 0) → Tₛ = 1 → log = 0 → XP = 0, on purpose.",
      isNot: "Not recency decay. Not the 0.99ⁿ standing leak. Do not rewrite as log(1+1/Tₛ).",
    },
    {
      id: "lambda",
      glyph: "λ",
      name: "Slam rate",
      is: "Knob inside Tₛ. Scales how fast the slam window opens with elapsed Δt.",
      isNot: "Not the standing leak.",
    },
    {
      id: "dt",
      glyph: "Δt",
      name: "Elapsed time of this loop",
      is: "Clock start to confirm. Clipped to Δt_cap so stalling is not a mint.",
      isNot: "Not calendar age of standing XP.",
    },
  ],
  other: [
    {
      id: "xp",
      glyph: "XP",
      name: "Global standing",
      is: "The letters are XP. Proxy of ΔS on the ledger after the mint. Every door can see that you have standing. You do not spend it. Access economy. Decays ~1%/month of remaining (0.99ⁿ). How XP works is planetary. A DFAO does not rewrite the mint. Cash-out is a lose-condition. If they vote that in, they forked.",
      isNot: "Not “Extropy Points.” Not a cash bag. Not ΔS itself. Not L. Not CT. Not Randall’s private ledger.",
    },
    {
      id: "script-f",
      glyph: "ℱ",
      name: "Falsifiability",
      is: "Script-F. A claim that can fail in the open. Lose-conditions live here.",
      isNot: "Not Frequency of Decay. Never write F for this.",
    },
    {
      id: "cl",
      glyph: "cₗ",
      name: "Causal-closure speed",
      is: "Local max rate causal effects propagate in a domain. Floor slogan: XP ≥ ΔS / cₗ². Compression of the mint, not a second theory.",
      isNot: "Not the speed of light as a new physics law. Structural analogy.",
    },
    {
      id: "l",
      glyph: "L",
      name: "Literal standing at this till",
      is: "First-class, like XP and CT. This moment, this DFAO, this store, this ticket. Built at the door: this-door CT against the house slider. Regular demand here vs a random spike. The slider is the house saying how much of that CT may count, and how much of the ticket the layer may touch. Optional auto: the box can park the slider from this till’s own proofs and load — same move as a hand, writes a vertex, house can override or kill. Domain bands (yes/no or band ≥ n per instrument) may be shown as ZKPs to this till. Same question as whether loops are closing here. Habits (walk vs Hummer) can become room modifiers later if that DFAO votes them in.",
      isNot: "Not sweeping floors. Not Landauer. Not a secret coupon. Not global XP. Not a mesh broadcast of the diary.",
    },
    {
      id: "ep",
      glyph: "EP",
      name: "Emergent Product",
      is: "Till spark. Born and burned in the sale. Early mesh: pennies off a fiat ticket. Dense mesh: can clear more of what you owe. Not a bag.",
      isNot: "Not Epistemic Proof. Letter collision. Proof-layer records do not buy milk.",
    },
    {
      id: "ct",
      glyph: "CT",
      name: "Community standing",
      is: "Meter for this door / this DFAO. Showing up here. Buying here. Being a node this house can plan around. Feeds L at the till. Not purchased with XP. This DFAO can vote how CT is scored inside this room. That vote does not rewrite CT next door.",
      isNot: "Not a coin. Not a job application. Not global XP. Not L itself.",
    },
    {
      id: "cat",
      glyph: "CAT",
      name: "Skill record",
      is: "Unique. Lane + level + issuer. Off the XP mint.",
      isNot: "Not a pile of points.",
    },
    {
      id: "it",
      glyph: "IT",
      name: "Influence standing",
      is: "Governance / demonstration weight. Idle leak ~5%/month. Off the XP mint.",
      isNot: "Not Insight Token. Not a bag.",
    },
    {
      id: "leak",
      glyph: "0.99ⁿ",
      name: "Standing leak",
      is: "~1% of remaining XP per ~30 days after settlement. Half-life ~69 months. Never hits zero in the reals.",
      isNot: "Not Tₛ. Not F.",
    },
  ],
} as const;
