/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as CharterRouteImport } from './routes/charter'
import { Route as DefaultsRouteImport } from './routes/defaults'
import { Route as DfaoRouteImport } from './routes/dfao'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HoaRouteImport } from './routes/hoa'
import { Route as IfThenRouteImport } from './routes/if-then'
import { Route as InsteadRouteImport } from './routes/instead'
import { Route as ItRouteImport } from './routes/it'
import { Route as KeyRouteImport } from './routes/key'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as MusicRouteImport } from './routes/music'
import { Route as BookRouteImport } from './routes/book'
import { Route as HowItRunsRouteImport } from './routes/how-it-runs'
import { Route as MathRouteImport } from './routes/math'
import { Route as MvtRouteImport } from './routes/mvt'
import { Route as OpenProblemsRouteImport } from './routes/open-problems'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ProofLayersRouteImport } from './routes/proof-layers'
import { Route as RedactedRouteImport } from './routes/redacted'
import { Route as ResearchPodRouteImport } from './routes/research-pod'
import { Route as RhoRouteImport } from './routes/rho'
import { Route as SayRouteImport } from './routes/say'
import { Route as SmartContractsRouteImport } from './routes/smart-contracts'
import { Route as TokenomicsRouteImport } from './routes/tokenomics'
import { Route as UniversaltimesRouteImport } from './routes/universaltimes'
import { Route as Web3RouteImport } from './routes/web3'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as PapersIndexRouteImport } from './routes/papers/index'
import { Route as HoaSunsetOaksRouteImport } from './routes/hoa.sunset-oaks'
import { Route as PapersClosingTheLoopRouteImport } from './routes/papers/closing-the-loop'
import { Route as PapersLiquidityAndDecayRouteImport } from './routes/papers/liquidity-and-decay'
import { Route as PodcastLogRouteImport } from './routes/podcast.log'
import { Route as PrintClosingTheLoopRouteImport } from './routes/print/closing-the-loop'
import { Route as StartIndexRouteImport } from './routes/start/index'
import { Route as StartAiRouteImport } from './routes/start/ai'
import { Route as StartGovernanceRouteImport } from './routes/start/governance'
import { Route as StartMoneyRouteImport } from './routes/start/money'
import { Route as StartPhysicsRouteImport } from './routes/start/physics'
import { Route as TokenomicsItRouteImport } from './routes/tokenomics.it'
import { Route as Web3GovernanceRouteImport } from './routes/web3.governance'
import { Route as Web3IdentityRouteImport } from './routes/web3.identity'
import { Route as Web3LoopRouteImport } from './routes/web3.loop'
import { Route as Web3NodeRouteImport } from './routes/web3.node'
import { Route as Web3TruthRouteImport } from './routes/web3.truth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterRoute = CharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultsRoute = DefaultsRouteImport.update({
  id: '/defaults',
  path: '/defaults',
  getParentRoute: () => rootRouteImport,
} as any)
const DfaoRoute = DfaoRouteImport.update({
  id: '/dfao',
  path: '/dfao',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HoaRoute = HoaRouteImport.update({
  id: '/hoa',
  path: '/hoa',
  getParentRoute: () => rootRouteImport,
} as any)
const IfThenRoute = IfThenRouteImport.update({
  id: '/if-then',
  path: '/if-then',
  getParentRoute: () => rootRouteImport,
} as any)
const InsteadRoute = InsteadRouteImport.update({
  id: '/instead',
  path: '/instead',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyRoute = KeyRouteImport.update({
  id: '/key',
  path: '/key',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItRunsRoute = HowItRunsRouteImport.update({
  id: '/how-it-runs',
  path: '/how-it-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const MathRoute = MathRouteImport.update({
  id: '/math',
  path: '/math',
  getParentRoute: () => rootRouteImport,
} as any)
const MvtRoute = MvtRouteImport.update({
  id: '/mvt',
  path: '/mvt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenProblemsRoute = OpenProblemsRouteImport.update({
  id: '/open-problems',
  path: '/open-problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofLayersRoute = ProofLayersRouteImport.update({
  id: '/proof-layers',
  path: '/proof-layers',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactedRoute = RedactedRouteImport.update({
  id: '/redacted',
  path: '/redacted',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPodRoute = ResearchPodRouteImport.update({
  id: '/research-pod',
  path: '/research-pod',
  getParentRoute: () => rootRouteImport,
} as any)
const RhoRoute = RhoRouteImport.update({
  id: '/rho',
  path: '/rho',
  getParentRoute: () => rootRouteImport,
} as any)
const SayRoute = SayRouteImport.update({
  id: '/say',
  path: '/say',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartContractsRoute = SmartContractsRouteImport.update({
  id: '/smart-contracts',
  path: '/smart-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenomicsRoute = TokenomicsRouteImport.update({
  id: '/tokenomics',
  path: '/tokenomics',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversaltimesRoute = UniversaltimesRouteImport.update({
  id: '/universaltimes',
  path: '/universaltimes',
  getParentRoute: () => rootRouteImport,
} as any)
const Web3Route = Web3RouteImport.update({
  id: '/web3',
  path: '/web3',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoaSunsetOaksRoute = HoaSunsetOaksRouteImport.update({
  id: '/sunset-oaks',
  path: '/sunset-oaks',
  getParentRoute: () => HoaRoute,
} as any)
const PapersClosingTheLoopRoute = PapersClosingTheLoopRouteImport.update({
  id: '/papers/closing-the-loop',
  path: '/papers/closing-the-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersLiquidityAndDecayRoute = PapersLiquidityAndDecayRouteImport.update({
  id: '/papers/liquidity-and-decay',
  path: '/papers/liquidity-and-decay',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastLogRoute = PodcastLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => PodcastRoute,
} as any)
const PrintClosingTheLoopRoute = PrintClosingTheLoopRouteImport.update({
  id: '/print/closing-the-loop',
  path: '/print/closing-the-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAiRoute = StartAiRouteImport.update({
  id: '/start/ai',
  path: '/start/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const StartGovernanceRoute = StartGovernanceRouteImport.update({
  id: '/start/governance',
  path: '/start/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const StartMoneyRoute = StartMoneyRouteImport.update({
  id: '/start/money',
  path: '/start/money',
  getParentRoute: () => rootRouteImport,
} as any)
const StartPhysicsRoute = StartPhysicsRouteImport.update({
  id: '/start/physics',
  path: '/start/physics',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenomicsItRoute = TokenomicsItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => TokenomicsRoute,
} as any)
const Web3GovernanceRoute = Web3GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => Web3Route,
} as any)
const Web3IdentityRoute = Web3IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => Web3Route,
} as any)
const Web3LoopRoute = Web3LoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => Web3Route,
} as any)
const Web3NodeRoute = Web3NodeRouteImport.update({
  id: '/node',
  path: '/node',
  getParentRoute: () => Web3Route,
} as any)
const Web3TruthRoute = Web3TruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => Web3Route,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/charter': typeof CharterRoute
  '/defaults': typeof DefaultsRoute
  '/dfao': typeof DfaoRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/hoa': typeof HoaRouteWithChildren
  '/if-then': typeof IfThenRoute
  '/instead': typeof InsteadRoute
  '/it': typeof ItRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/lyrics': typeof LyricsRoute
  '/music': typeof MusicRoute
  '/book': typeof BookRoute
  '/how-it-runs': typeof HowItRunsRoute
  '/math': typeof MathRoute
  '/mvt': typeof MvtRoute
  '/open-problems': typeof OpenProblemsRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/proof-layers': typeof ProofLayersRoute
  '/redacted': typeof RedactedRoute
  '/research-pod': typeof ResearchPodRoute
  '/rho': typeof RhoRoute
  '/say': typeof SayRoute
  '/smart-contracts': typeof SmartContractsRoute
  '/tokenomics': typeof TokenomicsRouteWithChildren
  '/universaltimes': typeof UniversaltimesRoute
  '/web3': typeof Web3RouteWithChildren
  '/hoa/sunset-oaks': typeof HoaSunsetOaksRoute
  '/papers/closing-the-loop': typeof PapersClosingTheLoopRoute
  '/papers/liquidity-and-decay': typeof PapersLiquidityAndDecayRoute
  '/podcast/log': typeof PodcastLogRoute
  '/print/closing-the-loop': typeof PrintClosingTheLoopRoute
  '/start/ai': typeof StartAiRoute
  '/start/governance': typeof StartGovernanceRoute
  '/start/money': typeof StartMoneyRoute
  '/start/physics': typeof StartPhysicsRoute
  '/tokenomics/it': typeof TokenomicsItRoute
  '/web3/governance': typeof Web3GovernanceRoute
  '/web3/identity': typeof Web3IdentityRoute
  '/web3/loop': typeof Web3LoopRoute
  '/web3/node': typeof Web3NodeRoute
  '/web3/truth': typeof Web3TruthRoute
  '/docs/': typeof DocsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/charter': typeof CharterRoute
  '/defaults': typeof DefaultsRoute
  '/dfao': typeof DfaoRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/hoa': typeof HoaRouteWithChildren
  '/if-then': typeof IfThenRoute
  '/instead': typeof InsteadRoute
  '/it': typeof ItRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/lyrics': typeof LyricsRoute
  '/music': typeof MusicRoute
  '/book': typeof BookRoute
  '/how-it-runs': typeof HowItRunsRoute
  '/math': typeof MathRoute
  '/mvt': typeof MvtRoute
  '/open-problems': typeof OpenProblemsRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/proof-layers': typeof ProofLayersRoute
  '/redacted': typeof RedactedRoute
  '/research-pod': typeof ResearchPodRoute
  '/rho': typeof RhoRoute
  '/say': typeof SayRoute
  '/smart-contracts': typeof SmartContractsRoute
  '/tokenomics': typeof TokenomicsRouteWithChildren
  '/universaltimes': typeof UniversaltimesRoute
  '/web3': typeof Web3RouteWithChildren
  '/hoa/sunset-oaks': typeof HoaSunsetOaksRoute
  '/papers/closing-the-loop': typeof PapersClosingTheLoopRoute
  '/papers/liquidity-and-decay': typeof PapersLiquidityAndDecayRoute
  '/podcast/log': typeof PodcastLogRoute
  '/print/closing-the-loop': typeof PrintClosingTheLoopRoute
  '/start/ai': typeof StartAiRoute
  '/start/governance': typeof StartGovernanceRoute
  '/start/money': typeof StartMoneyRoute
  '/start/physics': typeof StartPhysicsRoute
  '/tokenomics/it': typeof TokenomicsItRoute
  '/web3/governance': typeof Web3GovernanceRoute
  '/web3/identity': typeof Web3IdentityRoute
  '/web3/loop': typeof Web3LoopRoute
  '/web3/node': typeof Web3NodeRoute
  '/web3/truth': typeof Web3TruthRoute
  '/docs': typeof DocsIndexRoute
  '/papers': typeof PapersIndexRoute
  '/start': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/charter': typeof CharterRoute
  '/defaults': typeof DefaultsRoute
  '/dfao': typeof DfaoRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/hoa': typeof HoaRouteWithChildren
  '/if-then': typeof IfThenRoute
  '/instead': typeof InsteadRoute
  '/it': typeof ItRoute
  '/key': typeof KeyRoute
  '/login': typeof LoginRoute
  '/lyrics': typeof LyricsRoute
  '/music': typeof MusicRoute
  '/book': typeof BookRoute
  '/how-it-runs': typeof HowItRunsRoute
  '/math': typeof MathRoute
  '/mvt': typeof MvtRoute
  '/open-problems': typeof OpenProblemsRoute
  '/podcast': typeof PodcastRouteWithChildren
  '/proof-layers': typeof ProofLayersRoute
  '/redacted': typeof RedactedRoute
  '/research-pod': typeof ResearchPodRoute
  '/rho': typeof RhoRoute
  '/say': typeof SayRoute
  '/smart-contracts': typeof SmartContractsRoute
  '/tokenomics': typeof TokenomicsRouteWithChildren
  '/universaltimes': typeof UniversaltimesRoute
  '/web3': typeof Web3RouteWithChildren
  '/hoa/sunset-oaks': typeof HoaSunsetOaksRoute
  '/papers/closing-the-loop': typeof PapersClosingTheLoopRoute
  '/papers/liquidity-and-decay': typeof PapersLiquidityAndDecayRoute
  '/podcast/log': typeof PodcastLogRoute
  '/print/closing-the-loop': typeof PrintClosingTheLoopRoute
  '/start/ai': typeof StartAiRoute
  '/start/governance': typeof StartGovernanceRoute
  '/start/money': typeof StartMoneyRoute
  '/start/physics': typeof StartPhysicsRoute
  '/tokenomics/it': typeof TokenomicsItRoute
  '/web3/governance': typeof Web3GovernanceRoute
  '/web3/identity': typeof Web3IdentityRoute
  '/web3/loop': typeof Web3LoopRoute
  '/web3/node': typeof Web3NodeRoute
  '/web3/truth': typeof Web3TruthRoute
  '/docs/': typeof DocsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/charter'
    | '/defaults'
    | '/dfao'
    | '/faq'
    | '/glossary'
    | '/hoa'
    | '/if-then'
    | '/instead'
    | '/it'
    | '/key'
    | '/login'
    | '/lyrics'
    | '/music'
    | '/book'
    | '/how-it-runs'
    | '/music'
    | '/book'
    | '/how-it-runs'
    | '/math'
    | '/mvt'
    | '/open-problems'
    | '/podcast'
    | '/proof-layers'
    | '/redacted'
    | '/research-pod'
    | '/rho'
    | '/say'
    | '/smart-contracts'
    | '/tokenomics'
    | '/universaltimes'
    | '/web3'
    | '/hoa/sunset-oaks'
    | '/papers/closing-the-loop'
    | '/papers/liquidity-and-decay'
    | '/podcast/log'
    | '/print/closing-the-loop'
    | '/start/ai'
    | '/start/governance'
    | '/start/money'
    | '/start/physics'
    | '/tokenomics/it'
    | '/web3/governance'
    | '/web3/identity'
    | '/web3/loop'
    | '/web3/node'
    | '/web3/truth'
    | '/docs/'
    | '/papers/'
    | '/start/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/charter'
    | '/defaults'
    | '/dfao'
    | '/faq'
    | '/glossary'
    | '/hoa'
    | '/if-then'
    | '/instead'
    | '/it'
    | '/key'
    | '/login'
    | '/lyrics'
    | '/music'
    | '/book'
    | '/how-it-runs'
    | '/music'
    | '/book'
    | '/how-it-runs'
    | '/math'
    | '/mvt'
    | '/open-problems'
    | '/podcast'
    | '/proof-layers'
    | '/redacted'
    | '/research-pod'
    | '/rho'
    | '/say'
    | '/smart-contracts'
    | '/tokenomics'
    | '/universaltimes'
    | '/web3'
    | '/hoa/sunset-oaks'
    | '/papers/closing-the-loop'
    | '/papers/liquidity-and-decay'
    | '/podcast/log'
    | '/print/closing-the-loop'
    | '/start/ai'
    | '/start/governance'
    | '/start/money'
    | '/start/physics'
    | '/tokenomics/it'
    | '/web3/governance'
    | '/web3/identity'
    | '/web3/loop'
    | '/web3/node'
    | '/web3/truth'
    | '/docs'
    | '/papers'
    | '/start'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/charter'
    | '/defaults'
    | '/dfao'
    | '/faq'
    | '/glossary'
    | '/hoa'
    | '/if-then'
    | '/instead'
    | '/it'
    | '/key'
    | '/login'
    | '/lyrics'
    | '/music'
    | '/book'
    | '/how-it-runs'
    | '/music'
    | '/book'
    | '/how-it-runs'
    | '/math'
    | '/mvt'
    | '/open-problems'
    | '/podcast'
    | '/proof-layers'
    | '/redacted'
    | '/research-pod'
    | '/rho'
    | '/say'
    | '/smart-contracts'
    | '/tokenomics'
    | '/universaltimes'
    | '/web3'
    | '/hoa/sunset-oaks'
    | '/papers/closing-the-loop'
    | '/papers/liquidity-and-decay'
    | '/podcast/log'
    | '/print/closing-the-loop'
    | '/start/ai'
    | '/start/governance'
    | '/start/money'
    | '/start/physics'
    | '/tokenomics/it'
    | '/web3/governance'
    | '/web3/identity'
    | '/web3/loop'
    | '/web3/node'
    | '/web3/truth'
    | '/docs/'
    | '/papers/'
    | '/start/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  CharterRoute: typeof CharterRoute
  DefaultsRoute: typeof DefaultsRoute
  DfaoRoute: typeof DfaoRoute
  FaqRoute: typeof FaqRoute
  GlossaryRoute: typeof GlossaryRoute
  HoaRoute: typeof HoaRouteWithChildren
  IfThenRoute: typeof IfThenRoute
  InsteadRoute: typeof InsteadRoute
  ItRoute: typeof ItRoute
  KeyRoute: typeof KeyRoute
  LoginRoute: typeof LoginRoute
  LyricsRoute: typeof LyricsRoute
  MusicRoute: typeof MusicRoute
  BookRoute: typeof BookRoute
  HowItRunsRoute: typeof HowItRunsRoute
  MathRoute: typeof MathRoute
  MvtRoute: typeof MvtRoute
  OpenProblemsRoute: typeof OpenProblemsRoute
  PodcastRoute: typeof PodcastRouteWithChildren
  ProofLayersRoute: typeof ProofLayersRoute
  RedactedRoute: typeof RedactedRoute
  ResearchPodRoute: typeof ResearchPodRoute
  RhoRoute: typeof RhoRoute
  SayRoute: typeof SayRoute
  SmartContractsRoute: typeof SmartContractsRoute
  TokenomicsRoute: typeof TokenomicsRouteWithChildren
  UniversaltimesRoute: typeof UniversaltimesRoute
  Web3Route: typeof Web3RouteWithChildren
  PapersClosingTheLoopRoute: typeof PapersClosingTheLoopRoute
  PapersLiquidityAndDecayRoute: typeof PapersLiquidityAndDecayRoute
  PrintClosingTheLoopRoute: typeof PrintClosingTheLoopRoute
  StartAiRoute: typeof StartAiRoute
  StartGovernanceRoute: typeof StartGovernanceRoute
  StartMoneyRoute: typeof StartMoneyRoute
  StartPhysicsRoute: typeof StartPhysicsRoute
  DocsIndexRoute: typeof DocsIndexRoute
  PapersIndexRoute: typeof PapersIndexRoute
  StartIndexRoute: typeof StartIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter': {
      id: '/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defaults': {
      id: '/defaults'
      path: '/defaults'
      fullPath: '/defaults'
      preLoaderRoute: typeof DefaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dfao': {
      id: '/dfao'
      path: '/dfao'
      fullPath: '/dfao'
      preLoaderRoute: typeof DfaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoa': {
      id: '/hoa'
      path: '/hoa'
      fullPath: '/hoa'
      preLoaderRoute: typeof HoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/if-then': {
      id: '/if-then'
      path: '/if-then'
      fullPath: '/if-then'
      preLoaderRoute: typeof IfThenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instead': {
      id: '/instead'
      path: '/instead'
      fullPath: '/instead'
      preLoaderRoute: typeof InsteadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key': {
      id: '/key'
      path: '/key'
      fullPath: '/key'
      preLoaderRoute: typeof KeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-runs': {
      id: '/how-it-runs'
      path: '/how-it-runs'
      fullPath: '/how-it-runs'
      preLoaderRoute: typeof HowItRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math': {
      id: '/math'
      path: '/math'
      fullPath: '/math'
      preLoaderRoute: typeof MathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mvt': {
      id: '/mvt'
      path: '/mvt'
      fullPath: '/mvt'
      preLoaderRoute: typeof MvtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-problems': {
      id: '/open-problems'
      path: '/open-problems'
      fullPath: '/open-problems'
      preLoaderRoute: typeof OpenProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-layers': {
      id: '/proof-layers'
      path: '/proof-layers'
      fullPath: '/proof-layers'
      preLoaderRoute: typeof ProofLayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacted': {
      id: '/redacted'
      path: '/redacted'
      fullPath: '/redacted'
      preLoaderRoute: typeof RedactedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-pod': {
      id: '/research-pod'
      path: '/research-pod'
      fullPath: '/research-pod'
      preLoaderRoute: typeof ResearchPodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rho': {
      id: '/rho'
      path: '/rho'
      fullPath: '/rho'
      preLoaderRoute: typeof RhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/say': {
      id: '/say'
      path: '/say'
      fullPath: '/say'
      preLoaderRoute: typeof SayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-contracts': {
      id: '/smart-contracts'
      path: '/smart-contracts'
      fullPath: '/smart-contracts'
      preLoaderRoute: typeof SmartContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenomics': {
      id: '/tokenomics'
      path: '/tokenomics'
      fullPath: '/tokenomics'
      preLoaderRoute: typeof TokenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universaltimes': {
      id: '/universaltimes'
      path: '/universaltimes'
      fullPath: '/universaltimes'
      preLoaderRoute: typeof UniversaltimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web3': {
      id: '/web3'
      path: '/web3'
      fullPath: '/web3'
      preLoaderRoute: typeof Web3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoa/sunset-oaks': {
      id: '/hoa/sunset-oaks'
      path: '/sunset-oaks'
      fullPath: '/hoa/sunset-oaks'
      preLoaderRoute: typeof HoaSunsetOaksRouteImport
      parentRoute: typeof HoaRoute
    }
    '/papers/closing-the-loop': {
      id: '/papers/closing-the-loop'
      path: '/papers/closing-the-loop'
      fullPath: '/papers/closing-the-loop'
      preLoaderRoute: typeof PapersClosingTheLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/liquidity-and-decay': {
      id: '/papers/liquidity-and-decay'
      path: '/papers/liquidity-and-decay'
      fullPath: '/papers/liquidity-and-decay'
      preLoaderRoute: typeof PapersLiquidityAndDecayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/log': {
      id: '/podcast/log'
      path: '/log'
      fullPath: '/podcast/log'
      preLoaderRoute: typeof PodcastLogRouteImport
      parentRoute: typeof PodcastRoute
    }
    '/print/closing-the-loop': {
      id: '/print/closing-the-loop'
      path: '/print/closing-the-loop'
      fullPath: '/print/closing-the-loop'
      preLoaderRoute: typeof PrintClosingTheLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start/'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/ai': {
      id: '/start/ai'
      path: '/start/ai'
      fullPath: '/start/ai'
      preLoaderRoute: typeof StartAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/governance': {
      id: '/start/governance'
      path: '/start/governance'
      fullPath: '/start/governance'
      preLoaderRoute: typeof StartGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/money': {
      id: '/start/money'
      path: '/start/money'
      fullPath: '/start/money'
      preLoaderRoute: typeof StartMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/physics': {
      id: '/start/physics'
      path: '/start/physics'
      fullPath: '/start/physics'
      preLoaderRoute: typeof StartPhysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenomics/it': {
      id: '/tokenomics/it'
      path: '/it'
      fullPath: '/tokenomics/it'
      preLoaderRoute: typeof TokenomicsItRouteImport
      parentRoute: typeof TokenomicsRoute
    }
    '/web3/governance': {
      id: '/web3/governance'
      path: '/governance'
      fullPath: '/web3/governance'
      preLoaderRoute: typeof Web3GovernanceRouteImport
      parentRoute: typeof Web3Route
    }
    '/web3/identity': {
      id: '/web3/identity'
      path: '/identity'
      fullPath: '/web3/identity'
      preLoaderRoute: typeof Web3IdentityRouteImport
      parentRoute: typeof Web3Route
    }
    '/web3/loop': {
      id: '/web3/loop'
      path: '/loop'
      fullPath: '/web3/loop'
      preLoaderRoute: typeof Web3LoopRouteImport
      parentRoute: typeof Web3Route
    }
    '/web3/node': {
      id: '/web3/node'
      path: '/node'
      fullPath: '/web3/node'
      preLoaderRoute: typeof Web3NodeRouteImport
      parentRoute: typeof Web3Route
    }
    '/web3/truth': {
      id: '/web3/truth'
      path: '/truth'
      fullPath: '/web3/truth'
      preLoaderRoute: typeof Web3TruthRouteImport
      parentRoute: typeof Web3Route
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HoaRouteChildren {
  HoaSunsetOaksRoute: typeof HoaSunsetOaksRoute
}

const HoaRouteChildren: HoaRouteChildren = {
  HoaSunsetOaksRoute: HoaSunsetOaksRoute,
}

const HoaRouteWithChildren = HoaRoute._addFileChildren(HoaRouteChildren)

interface PodcastRouteChildren {
  PodcastLogRoute: typeof PodcastLogRoute
}

const PodcastRouteChildren: PodcastRouteChildren = {
  PodcastLogRoute: PodcastLogRoute,
}

const PodcastRouteWithChildren =
  PodcastRoute._addFileChildren(PodcastRouteChildren)

interface TokenomicsRouteChildren {
  TokenomicsItRoute: typeof TokenomicsItRoute
}

const TokenomicsRouteChildren: TokenomicsRouteChildren = {
  TokenomicsItRoute: TokenomicsItRoute,
}

const TokenomicsRouteWithChildren = TokenomicsRoute._addFileChildren(
  TokenomicsRouteChildren,
)

interface Web3RouteChildren {
  Web3GovernanceRoute: typeof Web3GovernanceRoute
  Web3IdentityRoute: typeof Web3IdentityRoute
  Web3LoopRoute: typeof Web3LoopRoute
  Web3NodeRoute: typeof Web3NodeRoute
  Web3TruthRoute: typeof Web3TruthRoute
}

const Web3RouteChildren: Web3RouteChildren = {
  Web3GovernanceRoute: Web3GovernanceRoute,
  Web3IdentityRoute: Web3IdentityRoute,
  Web3LoopRoute: Web3LoopRoute,
  Web3NodeRoute: Web3NodeRoute,
  Web3TruthRoute: Web3TruthRoute,
}

const Web3RouteWithChildren = Web3Route._addFileChildren(Web3RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  CharterRoute: CharterRoute,
  DefaultsRoute: DefaultsRoute,
  DfaoRoute: DfaoRoute,
  FaqRoute: FaqRoute,
  GlossaryRoute: GlossaryRoute,
  HoaRoute: HoaRouteWithChildren,
  IfThenRoute: IfThenRoute,
  InsteadRoute: InsteadRoute,
  ItRoute: ItRoute,
  KeyRoute: KeyRoute,
  LoginRoute: LoginRoute,
  LyricsRoute: LyricsRoute,
  MusicRoute: MusicRoute,
  BookRoute: BookRoute,
  HowItRunsRoute: HowItRunsRoute,
  MathRoute: MathRoute,
  MvtRoute: MvtRoute,
  OpenProblemsRoute: OpenProblemsRoute,
  PodcastRoute: PodcastRouteWithChildren,
  ProofLayersRoute: ProofLayersRoute,
  RedactedRoute: RedactedRoute,
  ResearchPodRoute: ResearchPodRoute,
  RhoRoute: RhoRoute,
  SayRoute: SayRoute,
  SmartContractsRoute: SmartContractsRoute,
  TokenomicsRoute: TokenomicsRouteWithChildren,
  UniversaltimesRoute: UniversaltimesRoute,
  Web3Route: Web3RouteWithChildren,
  PapersClosingTheLoopRoute: PapersClosingTheLoopRoute,
  PapersLiquidityAndDecayRoute: PapersLiquidityAndDecayRoute,
  PrintClosingTheLoopRoute: PrintClosingTheLoopRoute,
  StartAiRoute: StartAiRoute,
  StartGovernanceRoute: StartGovernanceRoute,
  StartMoneyRoute: StartMoneyRoute,
  StartPhysicsRoute: StartPhysicsRoute,
  DocsIndexRoute: DocsIndexRoute,
  PapersIndexRoute: PapersIndexRoute,
  StartIndexRoute: StartIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
