/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DfaoRouteImport } from './routes/dfao'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MvtRouteImport } from './routes/mvt'
import { Route as OpenProblemsRouteImport } from './routes/open-problems'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as ProofLayersRouteImport } from './routes/proof-layers'
import { Route as SayRouteImport } from './routes/say'
import { Route as UniversaltimesRouteImport } from './routes/universaltimes'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as PapersClosingTheLoopRouteImport } from './routes/papers/closing-the-loop'
import { Route as PrintClosingTheLoopRouteImport } from './routes/print/closing-the-loop'
import { Route as StartIndexRouteImport } from './routes/start/index'
import { Route as StartAiRouteImport } from './routes/start/ai'
import { Route as StartGovernanceRouteImport } from './routes/start/governance'
import { Route as StartMoneyRouteImport } from './routes/start/money'
import { Route as StartPhysicsRouteImport } from './routes/start/physics'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DfaoRoute = DfaoRouteImport.update({
  id: '/dfao',
  path: '/dfao',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MvtRoute = MvtRouteImport.update({
  id: '/mvt',
  path: '/mvt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenProblemsRoute = OpenProblemsRouteImport.update({
  id: '/open-problems',
  path: '/open-problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofLayersRoute = ProofLayersRouteImport.update({
  id: '/proof-layers',
  path: '/proof-layers',
  getParentRoute: () => rootRouteImport,
} as any)
const SayRoute = SayRouteImport.update({
  id: '/say',
  path: '/say',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversaltimesRoute = UniversaltimesRouteImport.update({
  id: '/universaltimes',
  path: '/universaltimes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersClosingTheLoopRoute = PapersClosingTheLoopRouteImport.update({
  id: '/papers/closing-the-loop',
  path: '/papers/closing-the-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintClosingTheLoopRoute = PrintClosingTheLoopRouteImport.update({
  id: '/print/closing-the-loop',
  path: '/print/closing-the-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartAiRoute = StartAiRouteImport.update({
  id: '/start/ai',
  path: '/start/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const StartGovernanceRoute = StartGovernanceRouteImport.update({
  id: '/start/governance',
  path: '/start/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const StartMoneyRoute = StartMoneyRouteImport.update({
  id: '/start/money',
  path: '/start/money',
  getParentRoute: () => rootRouteImport,
} as any)
const StartPhysicsRoute = StartPhysicsRouteImport.update({
  id: '/start/physics',
  path: '/start/physics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dfao': typeof DfaoRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/mvt': typeof MvtRoute
  '/open-problems': typeof OpenProblemsRoute
  '/podcast': typeof PodcastRoute
  '/proof-layers': typeof ProofLayersRoute
  '/say': typeof SayRoute
  '/universaltimes': typeof UniversaltimesRoute
  '/papers/closing-the-loop': typeof PapersClosingTheLoopRoute
  '/print/closing-the-loop': typeof PrintClosingTheLoopRoute
  '/start/ai': typeof StartAiRoute
  '/start/governance': typeof StartGovernanceRoute
  '/start/money': typeof StartMoneyRoute
  '/start/physics': typeof StartPhysicsRoute
  '/docs/': typeof DocsIndexRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dfao': typeof DfaoRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/mvt': typeof MvtRoute
  '/open-problems': typeof OpenProblemsRoute
  '/podcast': typeof PodcastRoute
  '/proof-layers': typeof ProofLayersRoute
  '/say': typeof SayRoute
  '/universaltimes': typeof UniversaltimesRoute
  '/papers/closing-the-loop': typeof PapersClosingTheLoopRoute
  '/print/closing-the-loop': typeof PrintClosingTheLoopRoute
  '/start/ai': typeof StartAiRoute
  '/start/governance': typeof StartGovernanceRoute
  '/start/money': typeof StartMoneyRoute
  '/start/physics': typeof StartPhysicsRoute
  '/docs': typeof DocsIndexRoute
  '/start': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dfao': typeof DfaoRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/mvt': typeof MvtRoute
  '/open-problems': typeof OpenProblemsRoute
  '/podcast': typeof PodcastRoute
  '/proof-layers': typeof ProofLayersRoute
  '/say': typeof SayRoute
  '/universaltimes': typeof UniversaltimesRoute
  '/papers/closing-the-loop': typeof PapersClosingTheLoopRoute
  '/print/closing-the-loop': typeof PrintClosingTheLoopRoute
  '/start/ai': typeof StartAiRoute
  '/start/governance': typeof StartGovernanceRoute
  '/start/money': typeof StartMoneyRoute
  '/start/physics': typeof StartPhysicsRoute
  '/docs/': typeof DocsIndexRoute
  '/start/': typeof StartIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dfao'
    | '/glossary'
    | '/login'
    | '/mvt'
    | '/open-problems'
    | '/podcast'
    | '/proof-layers'
    | '/say'
    | '/universaltimes'
    | '/papers/closing-the-loop'
    | '/print/closing-the-loop'
    | '/start/ai'
    | '/start/governance'
    | '/start/money'
    | '/start/physics'
    | '/docs/'
    | '/start/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dfao'
    | '/glossary'
    | '/login'
    | '/mvt'
    | '/open-problems'
    | '/podcast'
    | '/proof-layers'
    | '/say'
    | '/universaltimes'
    | '/papers/closing-the-loop'
    | '/print/closing-the-loop'
    | '/start/ai'
    | '/start/governance'
    | '/start/money'
    | '/start/physics'
    | '/docs'
    | '/start'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/dfao'
    | '/glossary'
    | '/login'
    | '/mvt'
    | '/open-problems'
    | '/podcast'
    | '/proof-layers'
    | '/say'
    | '/universaltimes'
    | '/papers/closing-the-loop'
    | '/print/closing-the-loop'
    | '/start/ai'
    | '/start/governance'
    | '/start/money'
    | '/start/physics'
    | '/docs/'
    | '/start/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DfaoRoute: typeof DfaoRoute
  GlossaryRoute: typeof GlossaryRoute
  LoginRoute: typeof LoginRoute
  MvtRoute: typeof MvtRoute
  OpenProblemsRoute: typeof OpenProblemsRoute
  PodcastRoute: typeof PodcastRoute
  ProofLayersRoute: typeof ProofLayersRoute
  SayRoute: typeof SayRoute
  UniversaltimesRoute: typeof UniversaltimesRoute
  PapersClosingTheLoopRoute: typeof PapersClosingTheLoopRoute
  PrintClosingTheLoopRoute: typeof PrintClosingTheLoopRoute
  StartAiRoute: typeof StartAiRoute
  StartGovernanceRoute: typeof StartGovernanceRoute
  StartMoneyRoute: typeof StartMoneyRoute
  StartPhysicsRoute: typeof StartPhysicsRoute
  DocsIndexRoute: typeof DocsIndexRoute
  StartIndexRoute: typeof StartIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dfao': {
      id: '/dfao'
      path: '/dfao'
      fullPath: '/dfao'
      preLoaderRoute: typeof DfaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mvt': {
      id: '/mvt'
      path: '/mvt'
      fullPath: '/mvt'
      preLoaderRoute: typeof MvtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-problems': {
      id: '/open-problems'
      path: '/open-problems'
      fullPath: '/open-problems'
      preLoaderRoute: typeof OpenProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof-layers': {
      id: '/proof-layers'
      path: '/proof-layers'
      fullPath: '/proof-layers'
      preLoaderRoute: typeof ProofLayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/say': {
      id: '/say'
      path: '/say'
      fullPath: '/say'
      preLoaderRoute: typeof SayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universaltimes': {
      id: '/universaltimes'
      path: '/universaltimes'
      fullPath: '/universaltimes'
      preLoaderRoute: typeof UniversaltimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/closing-the-loop': {
      id: '/papers/closing-the-loop'
      path: '/papers/closing-the-loop'
      fullPath: '/papers/closing-the-loop'
      preLoaderRoute: typeof PapersClosingTheLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/closing-the-loop': {
      id: '/print/closing-the-loop'
      path: '/print/closing-the-loop'
      fullPath: '/print/closing-the-loop'
      preLoaderRoute: typeof PrintClosingTheLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start/'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/ai': {
      id: '/start/ai'
      path: '/start/ai'
      fullPath: '/start/ai'
      preLoaderRoute: typeof StartAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/governance': {
      id: '/start/governance'
      path: '/start/governance'
      fullPath: '/start/governance'
      preLoaderRoute: typeof StartGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/money': {
      id: '/start/money'
      path: '/start/money'
      fullPath: '/start/money'
      preLoaderRoute: typeof StartMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/physics': {
      id: '/start/physics'
      path: '/start/physics'
      fullPath: '/start/physics'
      preLoaderRoute: typeof StartPhysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DfaoRoute: DfaoRoute,
  GlossaryRoute: GlossaryRoute,
  LoginRoute: LoginRoute,
  MvtRoute: MvtRoute,
  OpenProblemsRoute: OpenProblemsRoute,
  PodcastRoute: PodcastRoute,
  ProofLayersRoute: ProofLayersRoute,
  SayRoute: SayRoute,
  UniversaltimesRoute: UniversaltimesRoute,
  PapersClosingTheLoopRoute: PapersClosingTheLoopRoute,
  PrintClosingTheLoopRoute: PrintClosingTheLoopRoute,
  StartAiRoute: StartAiRoute,
  StartGovernanceRoute: StartGovernanceRoute,
  StartMoneyRoute: StartMoneyRoute,
  StartPhysicsRoute: StartPhysicsRoute,
  DocsIndexRoute: DocsIndexRoute,
  StartIndexRoute: StartIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
